export const trainingTypes = [
  "InitialTraining",
  "ApprenticeshipTraining",
  "SkillsValidation",
  "ContinuingEducation",
  "OnlineDistanceLearning",
  "DegreeProgram",
  "CertificationProgram",
  "OtherTraining",
]

export const trainingCategories = [
  "SalesPurchasing",
  "AirportOperations",
  "AgriFood",
  "PersonalAssistance",
  "Architecture",
  "Craftsmanship",
  "Auditing",
  "Healthcare",
  "BankingInsurance",
  "BeautyAestheticsHairdressing",
  "Construction",
  "OfficeAutomation",
  "Commerce",
  "Communication",
  "AccountingFinance",
  "Secretarial",
  "Publishing",
  "Electricity",
  "Education",
  "PublicService",
  "Management",
  "GraphicDesign",
  "Hospitality",
  "RealEstate",
  "Security",
  "InformationTechnology",
  "Legal",
  "Languages",
  "LogisticsTransportation",
  "Marketing",
  "Production",
  "QualityControl",
  "HumanResources",
  "Other",
]

export const fundingOptions = ["CPF", "EmployerFunded", "SelfFunded", "Other"]
