// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3voo0Cdm-kN3891rzRLTqoWDS6C1fODQ',
    appId: '1:166441708619:android:449c9fb5d4589e3a1b31ce',
    messagingSenderId: '166441708619',
    projectId: 'myreklam-7b2d9',
    storageBucket: 'myreklam-7b2d9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR5RvO_ME986BERLVC1uUD3iuXrAQSnP8',
    appId: '1:166441708619:ios:7ae549b1099b43a51b31ce',
    messagingSenderId: '166441708619',
    projectId: 'myreklam-7b2d9',
    storageBucket: 'myreklam-7b2d9.firebasestorage.app',
    androidClientId:
        '166441708619-e63s1vkkj2cbnqi43j542uscj94n5oid.apps.googleusercontent.com',
    iosClientId:
        '166441708619-o38o8rtne2rsie3ur6io1aq0finjtefs.apps.googleusercontent.com',
    iosBundleId: 'com.example.myreklam',
  );
}
