CREATE TABLE IF NOT EXISTS saved_searches (
  id VARCHAR(36) PRIMARY KEY,
  user_id VARCHAR(36) NOT NULL,
  search_name VARCHAR(255) NOT NULL,
  category VARCHAR(50) NOT NULL,
  deal_type VARCHAR(100),
  deal_category VARCHAR(100),
  sub_category VARCHAR(100),
  inquiry_type VARCHAR(100),
  inquiry_type_category VARCHAR(100),
  inquiry_training_category VARCHAR(100),
  real_estate_type VARCHAR(100),
  address VARCHAR(255),
  title VARCHAR(255),
  description TEXT,
  search_url TEXT,
  notification_enabled BOOLEAN DEFAULT TRUE,
  last_checked_at TIMESTAMP,
  new_matches_count INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_user_id (user_id),
  INDEX idx_category (category),
  INDEX idx_created_at (created_at)
);
